### ISSUE TITLE
发现一个下单(place)签名问题

### ISSUE THREAD

**Issue by Snipedl** [chengjk/fcoin-java-api#1]
您好, 我用了您的(FcoinApiClientImplTest)中例子, 大多数都是能直接跑通的; 其中 place方法, orders方法,运行时 出现 签名错误, 错误如下
ERROR com.fcoin.api.client.FcoinApiServiceGenerator - errMsg:api key check fail : {"status":1090,"msg":"Illegal API signature"}.
com.fcoin.api.client.exception.ApiException: errMsg:api key check fail : {"status":1090,"msg":"Illegal API signature"}.
	at com.fcoin.api.client.FcoinApiServiceGenerator.parseBody(FcoinApiServiceGenerator.java:75)
	at com.fcoin.api.client.FcoinApiServiceGenerator.executeSync(FcoinApiServiceGenerator.java:60)
	at com.fcoin.api.client.impl.FcoinApiRestClientImpl.place(FcoinApiRestClientImpl.java:73)
	at com.fcoin.api.client.impl.FcoinApiClientImplTest.place(FcoinApiClientImplTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

java.lang.IllegalStateException: invalid response from server.

	at com.fcoin.api.client.FcoinApiServiceGenerator.executeSync(FcoinApiServiceGenerator.java:68)
	at com.fcoin.api.client.impl.FcoinApiRestClientImpl.place(FcoinApiRestClientImpl.java:73)
	at com.fcoin.api.client.impl.FcoinApiClientImplTest.place(FcoinApiClientImplTest.java:108)

我运行了其他的, nodejs 代码, python 代码也都是, 报签名错误, 不知道是不是 Fcoin 官方API 文档有变化, 
麻烦大神解惑下, 您是不是下单获取订单都跑成功了, 还是我哪里设置的不对, 对应的 api.key 和 api.secret 都在Fcoin官网申请了,并且也写到代码中了,望大神指点下

**Comment by chengjk** [comment]
你好， orders 是我把一个参数给写错了，已经改正。 place，因为还没有有钱的账户，所有没有测试。 不过这边提示的不是签名问题。  我再分析下日志。

**Comment by chengjk** [comment]
place 方法我已经测试过了。更新下试试。
